/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tienda;

import Constructor.Usuario;
import com.placeholder.PlaceHolder; //Libreria usada para colocar placeholders en los text field
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class AgregarUsuario extends javax.swing.JFrame { //Clase usada para crear usuarios, tanto propietario como cliente.

    PlaceHolder holder;
    
    public AgregarUsuario() {
        initComponents();
        setTitle("Diagnostico De Paciente");
        setLocationRelativeTo(null);
        agregarPropietario.requestFocus();
        agregarPropietario.requestFocus();
        holder = new PlaceHolder(txt_nuevoNombre, "Ingrese el nombre de usuario"); //Uso del placeholder
        holder = new PlaceHolder(txt_nuevaContraseña, "Ingrese la contraseña de usuario"); 
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        agregarPropietario = new javax.swing.JLabel();
        txt_nuevoNombre = new javax.swing.JTextField();
        txt_nuevaContraseña = new javax.swing.JTextField();
        btn_nuevoNombre = new javax.swing.JButton();
        btn_limpiarPropietario = new javax.swing.JButton();
        cmb_nuevoTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 135, 113));

        agregarPropietario.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        agregarPropietario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarPropietario.setText("Agregar Usuario");

        txt_nuevoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nuevoNombreActionPerformed(evt);
            }
        });

        btn_nuevoNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/acep_norm.png"))); // NOI18N
        btn_nuevoNombre.setBorder(null);
        btn_nuevoNombre.setBorderPainted(false);
        btn_nuevoNombre.setContentAreaFilled(false);
        btn_nuevoNombre.setFocusPainted(false);
        btn_nuevoNombre.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/acep_press.png"))); // NOI18N
        btn_nuevoNombre.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/acep_roll.png"))); // NOI18N
        btn_nuevoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoNombreActionPerformed(evt);
            }
        });

        btn_limpiarPropietario.setBackground(new java.awt.Color(153, 204, 255));
        btn_limpiarPropietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/limpiar_norm.png"))); // NOI18N
        btn_limpiarPropietario.setBorder(null);
        btn_limpiarPropietario.setBorderPainted(false);
        btn_limpiarPropietario.setContentAreaFilled(false);
        btn_limpiarPropietario.setFocusPainted(false);
        btn_limpiarPropietario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/limpiar_press.png"))); // NOI18N
        btn_limpiarPropietario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/limpiar_roll.png"))); // NOI18N
        btn_limpiarPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarPropietarioActionPerformed(evt);
            }
        });

        cmb_nuevoTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija el usuario...", "Propietario", "Cliente" }));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/AgregarUsuario.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_nuevoNombre)
                        .addGap(57, 57, 57)
                        .addComponent(btn_limpiarPropietario)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(agregarPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_nuevaContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(txt_nuevoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(cmb_nuevoTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(101, 101, 101))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(agregarPropietario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addComponent(cmb_nuevoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_nuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_nuevaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_nuevoNombre)
                    .addComponent(btn_limpiarPropietario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nuevoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nuevoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nuevoNombreActionPerformed

    private void btn_nuevoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoNombreActionPerformed
        
        Login objLogin = new Login();
        
        String nombre = txt_nuevoNombre.getText();
        String contraseña = txt_nuevaContraseña.getText();
        int tipo = cmb_nuevoTipo.getSelectedIndex();

        if(nombre.equals("Ingrese el nombre de usuario")||contraseña.equals("Ingrese la contraseña")||tipo==0){ //Verifica que no existan campos vacios
            
            JOptionPane.showMessageDialog(null, "Error ! Verifique datos ingresados","SuperTienda",  JOptionPane.ERROR_MESSAGE);
            
        }else{
            
            Usuario nuevoUsuario = new Usuario(nombre, contraseña, tipo);
        
            Login.usuario.add(nuevoUsuario); //Se añade el nuevo usuario a la lista usuario

            objLogin.setVisible(true);
            dispose();
            
        }

    }//GEN-LAST:event_btn_nuevoNombreActionPerformed

    private void btn_limpiarPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarPropietarioActionPerformed
        
        //Coloca todos los datos por default
        txt_nuevoNombre.setText("");
        txt_nuevaContraseña.setText("");
        cmb_nuevoTipo.setSelectedIndex(0);
        holder = new PlaceHolder(txt_nuevoNombre, "Ingrese el nombre de usuario");
        holder = new PlaceHolder(txt_nuevaContraseña, "Ingrese la contraseña");
        
    }//GEN-LAST:event_btn_limpiarPropietarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel agregarPropietario;
    public javax.swing.JButton btn_limpiarPropietario;
    public javax.swing.JButton btn_nuevoNombre;
    private javax.swing.JComboBox<String> cmb_nuevoTipo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_nuevaContraseña;
    public javax.swing.JTextField txt_nuevoNombre;
    // End of variables declaration//GEN-END:variables
}
