/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tienda;

import Constructor.*;
import com.placeholder.PlaceHolder;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Login extends javax.swing.JFrame { //Clase usada para ejecutar la interfaz grafica del Login y validar el usuario.

    /**
     * Creates new form sad
     */
    
    public static Login objLogin = new Login();
    PlaceHolder holder;

    static LinkedList<Usuario>usuario= new LinkedList<Usuario>(); //Lista usuario 
    
    public Login() {
        initComponents();
        setTitle("SuperTienda");
        setLocationRelativeTo(null);
        inicioSesion.requestFocus(); //Se cambia el focus para poder observar el placeholder
        inicioSesion.requestFocus();
        holder = new PlaceHolder(txt_ingreseUsuario, "Ingrese el nombre de usuario");
        holder = new PlaceHolder(txt_ingreseContraseña, "Ingrese la contraseña de usuario");

    }
    
    public void cargarUsuarios(){ //Datos de pruba para usuarios, donde 1 es propietario y 2 es cliente
        
        Usuario us1 = new Usuario("Carlos", "123",1);
        Usuario us2 = new Usuario("Victor", "contraseña",1);
        Usuario us3 = new Usuario("Laura", "123contraseña",1);
        Usuario us4 = new Usuario("Marco", "prueba",2);
        Usuario us5 = new Usuario("Martha", "password",2);
        Usuario us6 = new Usuario("Luis", "12345",2);
        usuario.add(us1);
        usuario.add(us2);
        usuario.add(us3);
        usuario.add(us4);
        usuario.add(us5);
        usuario.add(us6);
        
    }
    
        
    public int verificarUsuario(String nombreComprobar, String contraseñaComprobar, int tipo){ //Metodo que valida el usuario ingresado.
        
        int flag = 0; //Variable que identificara si el usuario se encontro en la lista o no.
        for (int i = 0; i < usuario.size(); i++) {
            
            String nombre = usuario.get(i).getNombre(); //Se toma el nombre.
            String contraseña = usuario.get(i).getContraseña(); //Se toma la contraseña.
            int clase = usuario.get(i).getTipo(); //Se toma el tipo de usuario
            
            if (nombreComprobar.equals(nombre)&&contraseñaComprobar.equals(contraseña)&&clase==1){ /*Si la información ingresada en los campos es igual a
                                                                                                     un usuario guardado le da a la variable flag valor de 1*/
                
                flag = 1; //Si es propietario
                
            }else if (nombreComprobar.equals(nombre)&&contraseñaComprobar.equals(contraseña)&&clase==2){
                
                flag = 2; //Si es cliente
            }else{
                //Si esta errado envia 0
            }
            
        }
        
        return flag;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inicioSesion = new javax.swing.JLabel();
        txt_ingreseUsuario = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_añadir = new javax.swing.JButton();
        cmb_usuario = new javax.swing.JComboBox<>();
        txt_ingreseContraseña = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 135, 113));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Bienvenido a tienda SuperTienda");

        inicioSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicioSesion.setText("Inicio De Sesión");

        txt_ingreseUsuario.setToolTipText("");
        txt_ingreseUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ingreseUsuarioActionPerformed(evt);
            }
        });

        btn_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/acep_norm.png"))); // NOI18N
        btn_aceptar.setBorder(null);
        btn_aceptar.setBorderPainted(false);
        btn_aceptar.setContentAreaFilled(false);
        btn_aceptar.setFocusPainted(false);
        btn_aceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/acep_press.png"))); // NOI18N
        btn_aceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/acep_roll.png"))); // NOI18N
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/limpiar_norm.png"))); // NOI18N
        btn_limpiar.setToolTipText("");
        btn_limpiar.setBorder(null);
        btn_limpiar.setBorderPainted(false);
        btn_limpiar.setContentAreaFilled(false);
        btn_limpiar.setFocusPainted(false);
        btn_limpiar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/limpiar_press.png"))); // NOI18N
        btn_limpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/limpiar_roll.png"))); // NOI18N
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/add_norm.png"))); // NOI18N
        btn_añadir.setBorder(null);
        btn_añadir.setBorderPainted(false);
        btn_añadir.setContentAreaFilled(false);
        btn_añadir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_añadir.setFocusPainted(false);
        btn_añadir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/add_press.png"))); // NOI18N
        btn_añadir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/add_roll.png"))); // NOI18N
        btn_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirActionPerformed(evt);
            }
        });

        cmb_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija el usuario...", "Propietario", "Cliente" }));
        cmb_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_usuarioActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Bienvenido.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inicioSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(btn_aceptar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_limpiar))
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addComponent(btn_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_ingreseUsuario)
                                    .addComponent(cmb_usuario, 0, 192, Short.MAX_VALUE)
                                    .addComponent(txt_ingreseContraseña))
                                .addGap(90, 90, 90)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(inicioSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_ingreseUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_ingreseContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_aceptar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ingreseUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ingreseUsuarioActionPerformed
        
        
        
    }//GEN-LAST:event_txt_ingreseUsuarioActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        
        String nombreComprobar = txt_ingreseUsuario.getText();
        String contraseñaComprobar = txt_ingreseContraseña.getText();
        int clase = cmb_usuario.getSelectedIndex();

        int verificacion = objLogin.verificarUsuario(nombreComprobar, contraseñaComprobar, clase); //Llamado a la función verificadUsuario.

        if(clase==verificacion){
            switch (verificacion) {
            case 1://Si es propietario
                VistaPropietario objPropiertario = new VistaPropietario();
                objPropiertario.setVisible(true); //Se abre la vista de propietario.
                dispose(); //Se cierra la vista de Login.
            break;
            
            case 2://Si es cliente
                
                VistaCliente objCliente = new VistaCliente();                
                objCliente.usuarioProducto.setText(nombreComprobar); //
                objCliente.usuarioFiltrar.setText(nombreComprobar);  // Se le asigna al label el nombre del cliente
                objCliente.usuarioComprar.setText(nombreComprobar);  //
                objCliente.setVisible(true); //Se abre la vista cliente
                dispose();
                
            break;
            
            default://Si esta errada la información ingresada.
                JOptionPane.showMessageDialog(null, "Error ! Verifique datos ingresados","SuperTienda",  JOptionPane.ERROR_MESSAGE);
            break;
        }
        }else{
            JOptionPane.showMessageDialog(null, "Error ! Verifique datos ingresados","SuperTienda",  JOptionPane.ERROR_MESSAGE);
        }
                
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        
        //Restaura los valores poder defecto
        txt_ingreseUsuario.setText("");
        txt_ingreseContraseña.setText("");
        cmb_usuario.setSelectedIndex(0);
        holder = new PlaceHolder(txt_ingreseUsuario, "Ingrese el nombre de usuario");
        holder = new PlaceHolder(txt_ingreseContraseña, "Ingrese la contraseña");
        
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirActionPerformed
    
        AgregarUsuario objPropietario = new AgregarUsuario();
        objPropietario.setVisible(true); //Se abre la vista AgregarUsuario.
        dispose(); //Se cierra vista Login.
        
        
    }//GEN-LAST:event_btn_añadirActionPerformed

    private void cmb_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_usuarioActionPerformed
        

    }//GEN-LAST:event_cmb_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_aceptar;
    public javax.swing.JButton btn_añadir;
    public javax.swing.JButton btn_limpiar;
    private javax.swing.JComboBox<String> cmb_usuario;
    public javax.swing.JLabel inicioSesion;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_ingreseContraseña;
    public javax.swing.JTextField txt_ingreseUsuario;
    // End of variables declaration//GEN-END:variables
}
