/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tienda;

import Constructor.Producto;
import com.placeholder.PlaceHolder; //Importación de la libreria PlaceHolder para asignar placeholder a los textfield.
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class ModificarProducto extends javax.swing.JFrame { //Clase usada para modificar o eliminar un producto existente.

    /**
     * Creates new form ModificarProducto
     */
    PlaceHolder holder;
    
    public ModificarProducto() {
        initComponents();
        setTitle("SuperTienda");
        setLocationRelativeTo(null);
        modificarEliminar.requestFocus(); //Se cambia el focus para poder observar el placeholder
        modificarEliminar.requestFocus();
        holder = new PlaceHolder(txt_traeNombre, "Ingrese el nombre del producto");
        holder = new PlaceHolder(txt_traePrecio, "Ingrese el valor del producto");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        modificarEliminar = new javax.swing.JLabel();
        txt_traeNombre = new javax.swing.JTextField();
        txt_traePrecio = new javax.swing.JTextField();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        cmb_modificarCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 135, 113));

        modificarEliminar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        modificarEliminar.setText("Modificación/Eliminación Producto");

        txt_traeNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_traeNombreActionPerformed(evt);
            }
        });

        txt_traePrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_traePrecioActionPerformed(evt);
            }
        });

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/editar_norm.png"))); // NOI18N
        btn_editar.setBorder(null);
        btn_editar.setBorderPainted(false);
        btn_editar.setContentAreaFilled(false);
        btn_editar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/editar_press.png"))); // NOI18N
        btn_editar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/editar_roll.png"))); // NOI18N
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/eliminar_norm.png"))); // NOI18N
        btn_eliminar.setBorder(null);
        btn_eliminar.setBorderPainted(false);
        btn_eliminar.setContentAreaFilled(false);
        btn_eliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/eliminar_press.png"))); // NOI18N
        btn_eliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/eliminar_roll.png"))); // NOI18N
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        cmb_modificarCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir categoria...", "Camisa", "Camiseta", "Pantalón", "Vestido", "Zapatos", "Chaqueta", "Medias" }));
        cmb_modificarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_modificarCategoriaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Modificar.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(71, Short.MAX_VALUE)
                        .addComponent(modificarEliminar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btn_editar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_eliminar)))
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_traeNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(txt_traePrecio)
                    .addComponent(cmb_modificarCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(modificarEliminar)
                .addGap(41, 41, 41)
                .addComponent(txt_traeNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_traePrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmb_modificarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_eliminar)
                        .addComponent(btn_editar))
                    .addComponent(jLabel1))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        
        String producto = txt_traeNombre.getText();
        String precio2 = txt_traePrecio.getText();
        int tipo2 = cmb_modificarCategoria.getSelectedIndex();
        
        if(producto.equals("Ingrese el nombre del producto")||precio2.equals("Ingrese el valor del producto")||tipo2==0){ //Verifica que no existan campos vacios.
            
            JOptionPane.showMessageDialog(null, "Error ! Verifique datos ingresados","SuperTienda",  JOptionPane.ERROR_MESSAGE);
            
        }else{
        
        String decision = JOptionPane.showInputDialog("¿Seguro desea modificar el producto? Si/No");
        
        if(decision.toLowerCase().equals("si")){
            
            //Se toman los nuevos datos ingresados
            int aux = VistaPropietario.posicion;
            String nombre = txt_traeNombre.getText(); 
            String precio= txt_traePrecio.getText();
            int precioValor = Integer.parseInt(precio);
            int tipo = cmb_modificarCategoria.getSelectedIndex();
            Producto productoModificado = new Producto(nombre, tipo, precioValor);

            VistaPropietario.producto.set(aux, productoModificado); //Se envian los nuevos datos ingresados en la misma posición.

            VistaPropietario objPropietario = new VistaPropietario();
            objPropietario.setVisible(true); //Se devuelve a la vista propietario
            dispose();// Se cierra la vista ModificarProducto.
            
        }else if(decision.toLowerCase().equals("no")){
            
        }else{
            
            JOptionPane.showMessageDialog(null, "Error ! Respuesta no valida","SuperTienda",  JOptionPane.ERROR_MESSAGE);
            
        }
        }
        
    }//GEN-LAST:event_btn_editarActionPerformed

    private void txt_traeNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_traeNombreActionPerformed
        
        //txt_traeNombre.setText(VistaPropietario.nombreVerificado);
        
    }//GEN-LAST:event_txt_traeNombreActionPerformed

    private void txt_traePrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_traePrecioActionPerformed
        
        
    }//GEN-LAST:event_txt_traePrecioActionPerformed

    private void cmb_modificarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_modificarCategoriaActionPerformed
        
        
    }//GEN-LAST:event_cmb_modificarCategoriaActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        
        String decision = JOptionPane.showInputDialog("¿Seguro desea eliminar el producto? Si/No");
        
        if(decision.toLowerCase().equals("si")){
            
            int aux = VistaPropietario.posicion;
            VistaPropietario.producto.remove(aux); //Se elimina la posición de la lista.
            VistaPropietario objPropietario = new VistaPropietario();
            objPropietario.setVisible(true); //Se devuleve a la vista propietario.
            dispose(); //Se cierra la vista ModificarProducto.
            
        }else if(decision.toLowerCase().equals("no")){
            
        }else{
            
            JOptionPane.showMessageDialog(null, "Error ! Respuesta no valida","SuperTienda",  JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_btn_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_editar;
    public javax.swing.JButton btn_eliminar;
    public javax.swing.JComboBox<String> cmb_modificarCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel modificarEliminar;
    public javax.swing.JTextField txt_traeNombre;
    public javax.swing.JTextField txt_traePrecio;
    // End of variables declaration//GEN-END:variables
}
