/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tienda;

import Constructor.Producto;
import Constructor.Usuario;
import com.placeholder.PlaceHolder;
import java.util.Collections; //Importe de libreria de collecciones.
import java.util.LinkedList; // Importe de libreria para listas.
import java.util.Stack; //Importe libreria para pilas.
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class VistaPropietario extends javax.swing.JFrame { //Clase que ejecuta la vista de propietario, además de ejecutar todas sus funciones.

    /**
     * Creates new form VistaPropietario
     */
    
    PlaceHolder holder;

    static int posicion;
    static LinkedList<Producto>producto= new LinkedList<Producto>(); //Se declara la lista producto.
    static Stack<Producto>pila=new Stack<Producto>(); //Se declara la pila.
    
    public VistaPropietario() {
        initComponents();
        setTitle("SuperTienda");
        setLocationRelativeTo(null);
        datosProducto.requestFocus();
        datosProducto.requestFocus();
        holder = new PlaceHolder(txt_ingresarProducto, "Ingrese el nombre del producto");
        holder = new PlaceHolder(txt_ingresarPrecio, "Ingrese el valor del producto");
        holder = new PlaceHolder(txt_nombreModificar, "Ingrese el nombre del producto");
        holder = new PlaceHolder(txt_precioModificacion, "Ingrese el valor del producto");

    }
       
    public void cargarProducto(){ //Se cargan los productos de prueba.
        
        VistaCliente objCliente = new VistaCliente();
        
        Producto us1 = new Producto("Polo", 2,120000);
        Producto us2 = new Producto("Chevignon", 3,250000);
        Producto us3 = new Producto("Adidas", 5,180000);
        Producto us4 = new Producto("Gef", 1,100000);
        Producto us5 = new Producto("People", 7,60000);
        Producto us6 = new Producto("Koaj", 2,45000);
        producto.add(us1);//Se cargan en la lista.
        producto.add(us2);
        producto.add(us3);
        producto.add(us4);
        producto.add(us5);
        producto.add(us6);
        pila.push(us1); //Se cargan en la pila
        pila.push(us2);
        pila.push(us3);
        pila.push(us4);
        pila.push(us5);
        pila.push(us6);
        objCliente.cola.offer(us1); //Se cargan en la cola
        objCliente.cola.offer(us2);
        
    }
    
    public int verificarProducto(String nombreComprobar, String precioComprobar, int tipo){ //Verifica si el producto se encuentra guardado.
        
        int flag = 0;
        for (int i = 0; i < producto.size(); i++) {
            
            String nombre = producto.get(i).getProducto();
            int aux = producto.get(i).getPrecio();
            String precio = String.valueOf(aux);
            int clase = producto.get(i).getCategoria();
            
            if (nombreComprobar.equals(nombre)&&precioComprobar.equals(precio)&&tipo==clase){

                posicion = i;
                flag = 1;
                
            }
            
        }
        
        return flag;
    }
    
    public String devolverPrimero(){ //Metodo que regresa el primer elemento de la pila.
        
        String primero="";

        if(pila.isEmpty()){
            
        }else{
            
            primero = pila.firstElement().getProducto();
        }
           
        
        return primero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        datosProducto = new javax.swing.JLabel();
        txt_ingresarProducto = new javax.swing.JTextField();
        txt_ingresarPrecio = new javax.swing.JTextField();
        cmb_categoria = new javax.swing.JComboBox<>();
        btn_agregarProducto = new javax.swing.JButton();
        btn_limpiarProducto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        modificacionProducto = new javax.swing.JLabel();
        txt_nombreModificar = new javax.swing.JTextField();
        txt_precioModificacion = new javax.swing.JTextField();
        btn_aceptarModificacion = new javax.swing.JButton();
        btn_limpiarModificacion = new javax.swing.JButton();
        cmb_modificarEliminar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_mostrarProducto = new javax.swing.JTextArea();
        btn_actualizarLista = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        estadisticaTienda = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea_estadistica = new javax.swing.JTextArea();
        btn_actualizarEstadistica = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        solicitudes = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea_mostrarSolicitud = new javax.swing.JTextArea();
        atenderPrimero = new javax.swing.JLabel();
        actualizarCola = new javax.swing.JLabel();
        btn_aceptarSolicitud = new javax.swing.JButton();
        btn_actualizarSolicitud = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cerrarSesion = new javax.swing.JLabel();
        btn_salirPropietario = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(240, 135, 113));

        datosProducto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        datosProducto.setText("Datos Del Producto");

        txt_ingresarProducto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_ingresarProductoPropertyChange(evt);
            }
        });

        cmb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir categoria...", "Camisa", "Camiseta", "Pantalón", "Vestido", "Zapatos", "Chaqueta", "Medias" }));

        btn_agregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/acep_norm.png"))); // NOI18N
        btn_agregarProducto.setBorder(null);
        btn_agregarProducto.setBorderPainted(false);
        btn_agregarProducto.setContentAreaFilled(false);
        btn_agregarProducto.setFocusPainted(false);
        btn_agregarProducto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/acep_press.png"))); // NOI18N
        btn_agregarProducto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/acep_roll.png"))); // NOI18N
        btn_agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarProductoActionPerformed(evt);
            }
        });

        btn_limpiarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/limpiar_norm.png"))); // NOI18N
        btn_limpiarProducto.setBorder(null);
        btn_limpiarProducto.setBorderPainted(false);
        btn_limpiarProducto.setContentAreaFilled(false);
        btn_limpiarProducto.setFocusPainted(false);
        btn_limpiarProducto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/limpiar_press.png"))); // NOI18N
        btn_limpiarProducto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/limpiar_roll.png"))); // NOI18N
        btn_limpiarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarProductoActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/IngresarProducto.JPG"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/IngresarProducto2.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btn_agregarProducto)
                        .addGap(109, 109, 109)
                        .addComponent(btn_limpiarProducto))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ingresarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2)
                        .addGap(71, 71, 71)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datosProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_ingresarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(datosProducto)
                        .addGap(42, 42, 42)
                        .addComponent(txt_ingresarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2))))
                .addGap(17, 17, 17)
                .addComponent(txt_ingresarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_limpiarProducto)
                    .addComponent(btn_agregarProducto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Ingresar producto", jPanel3);

        jPanel4.setBackground(new java.awt.Color(240, 135, 113));

        modificacionProducto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        modificacionProducto.setText("Modificación/Eliminación Producto");

        txt_nombreModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreModificarActionPerformed(evt);
            }
        });

        btn_aceptarModificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/acep_norm.png"))); // NOI18N
        btn_aceptarModificacion.setAutoscrolls(true);
        btn_aceptarModificacion.setBorder(null);
        btn_aceptarModificacion.setBorderPainted(false);
        btn_aceptarModificacion.setContentAreaFilled(false);
        btn_aceptarModificacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/acep_press.png"))); // NOI18N
        btn_aceptarModificacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/acep_roll.png"))); // NOI18N
        btn_aceptarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarModificacionActionPerformed(evt);
            }
        });

        btn_limpiarModificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/limpiar_norm.png"))); // NOI18N
        btn_limpiarModificacion.setBorder(null);
        btn_limpiarModificacion.setBorderPainted(false);
        btn_limpiarModificacion.setContentAreaFilled(false);
        btn_limpiarModificacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/limpiar_press.png"))); // NOI18N
        btn_limpiarModificacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/limpiar_roll.png"))); // NOI18N
        btn_limpiarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarModificacionActionPerformed(evt);
            }
        });

        cmb_modificarEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir categoria...", "Camisa", "Camiseta", "Pantalón", "Vestido", "Zapatos", "Chaqueta", "Medias" }));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Modificar.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_aceptarModificacion)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addGap(37, 37, 37)
                        .addComponent(btn_limpiarModificacion))
                    .addComponent(modificacionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(157, 157, 157))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_nombreModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(txt_precioModificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(cmb_modificarEliminar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(222, 222, 222))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(modificacionProducto)
                .addGap(40, 40, 40)
                .addComponent(txt_nombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_precioModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmb_modificarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_aceptarModificacion, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_limpiarModificacion, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4))
                .addGap(47, 47, 47))
        );

        jTabbedPane2.addTab("Modificar/Eliminar producto", jPanel4);

        jPanel5.setBackground(new java.awt.Color(240, 135, 113));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Productos Ingresados");

        txtArea_mostrarProducto.setEditable(false);
        txtArea_mostrarProducto.setBackground(new java.awt.Color(240, 135, 113));
        txtArea_mostrarProducto.setColumns(20);
        txtArea_mostrarProducto.setRows(5);
        txtArea_mostrarProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 135, 113)));
        txtArea_mostrarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(txtArea_mostrarProducto);

        btn_actualizarLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/upd_norm.png"))); // NOI18N
        btn_actualizarLista.setBorder(null);
        btn_actualizarLista.setBorderPainted(false);
        btn_actualizarLista.setContentAreaFilled(false);
        btn_actualizarLista.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/upd_press.png"))); // NOI18N
        btn_actualizarLista.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/upd_roll.png"))); // NOI18N
        btn_actualizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarListaActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Lista.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btn_actualizarLista))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(135, 135, 135)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_actualizarLista)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Listar productos", jPanel5);

        jPanel1.setBackground(new java.awt.Color(240, 135, 113));

        estadisticaTienda.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        estadisticaTienda.setText("Estadisticas De La Tienda");

        txtArea_estadistica.setEditable(false);
        txtArea_estadistica.setBackground(new java.awt.Color(240, 135, 113));
        txtArea_estadistica.setColumns(20);
        txtArea_estadistica.setRows(5);
        jScrollPane2.setViewportView(txtArea_estadistica);

        btn_actualizarEstadistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/upd_norm.png"))); // NOI18N
        btn_actualizarEstadistica.setBorder(null);
        btn_actualizarEstadistica.setBorderPainted(false);
        btn_actualizarEstadistica.setContentAreaFilled(false);
        btn_actualizarEstadistica.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/upd_press.png"))); // NOI18N
        btn_actualizarEstadistica.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/upd_roll.png"))); // NOI18N
        btn_actualizarEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarEstadisticaActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Estadistica.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(btn_actualizarEstadistica))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(84, 84, 84)
                                .addComponent(estadisticaTienda))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(estadisticaTienda)
                        .addGap(8, 8, 8)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_actualizarEstadistica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Estadisticas", jPanel1);

        jPanel6.setBackground(new java.awt.Color(240, 135, 113));

        solicitudes.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        solicitudes.setText("Solicitudes");

        txtArea_mostrarSolicitud.setEditable(false);
        txtArea_mostrarSolicitud.setBackground(new java.awt.Color(240, 135, 113));
        txtArea_mostrarSolicitud.setColumns(20);
        txtArea_mostrarSolicitud.setRows(5);
        jScrollPane3.setViewportView(txtArea_mostrarSolicitud);

        atenderPrimero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        atenderPrimero.setText("Atender primero de la cola");

        actualizarCola.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        actualizarCola.setText("Actualizar cola");

        btn_aceptarSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/acep_norm.png"))); // NOI18N
        btn_aceptarSolicitud.setBorder(null);
        btn_aceptarSolicitud.setBorderPainted(false);
        btn_aceptarSolicitud.setContentAreaFilled(false);
        btn_aceptarSolicitud.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/acep_press.png"))); // NOI18N
        btn_aceptarSolicitud.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/acep_roll.png"))); // NOI18N
        btn_aceptarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarSolicitudActionPerformed(evt);
            }
        });

        btn_actualizarSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/upd_norm.png"))); // NOI18N
        btn_actualizarSolicitud.setBorder(null);
        btn_actualizarSolicitud.setBorderPainted(false);
        btn_actualizarSolicitud.setContentAreaFilled(false);
        btn_actualizarSolicitud.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/upd_press.png"))); // NOI18N
        btn_actualizarSolicitud.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/upd_roll.png"))); // NOI18N
        btn_actualizarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarSolicitudActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Carrito.JPG"))); // NOI18N
        jLabel7.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(atenderPrimero)
                .addGap(132, 132, 132)
                .addComponent(actualizarCola, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(btn_aceptarSolicitud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_actualizarSolicitud)
                .addGap(142, 142, 142))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(141, 141, 141)
                        .addComponent(solicitudes))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(solicitudes)
                        .addGap(8, 8, 8)))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atenderPrimero)
                    .addComponent(actualizarCola))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_actualizarSolicitud)
                    .addComponent(btn_aceptarSolicitud))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Solicitudes", jPanel6);

        jPanel7.setBackground(new java.awt.Color(240, 135, 113));

        cerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cerrarSesion.setText("Cerrar Sesión");

        btn_salirPropietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/salir_norm.png"))); // NOI18N
        btn_salirPropietario.setBorder(null);
        btn_salirPropietario.setBorderPainted(false);
        btn_salirPropietario.setContentAreaFilled(false);
        btn_salirPropietario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/salir_press.png"))); // NOI18N
        btn_salirPropietario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/salir_roll.png"))); // NOI18N
        btn_salirPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirPropietarioActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Cerrar_Sesion.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_salirPropietario)
                    .addComponent(cerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(cerrarSesion)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btn_salirPropietario)
                .addGap(108, 108, 108))
        );

        jTabbedPane2.addTab("Salir", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ingresarProductoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_ingresarProductoPropertyChange
        
    }//GEN-LAST:event_txt_ingresarProductoPropertyChange

    private void btn_limpiarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarProductoActionPerformed
         
        //Coloca los valores por default
        txt_ingresarProducto.setText("");
        txt_ingresarPrecio.setText("");
        cmb_categoria.setSelectedIndex(0);
        holder = new PlaceHolder(txt_ingresarProducto, "Ingrese el nombre del producto");
        holder = new PlaceHolder(txt_ingresarPrecio, "Ingrese el valor del producto");
        
    }//GEN-LAST:event_btn_limpiarProductoActionPerformed

    private void btn_agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarProductoActionPerformed
        
        String nombre = txt_ingresarProducto.getText();
        String precio = txt_ingresarPrecio.getText();
        int precioValor = Integer.parseInt(precio);
        int tipo = cmb_categoria.getSelectedIndex();       
        
        if(nombre.equals("Ingrese el nombre del producto")||precio.equals("Ingrese el valor del producto")||tipo==0){ //Verifica que no hayan campos vacios.
            
            JOptionPane.showMessageDialog(null, "Error ! Verifique datos ingresados","SuperTienda",  JOptionPane.ERROR_MESSAGE);
            
        }else{
           
            Producto nuevoProducto = new Producto(nombre, tipo, precioValor);
            producto.add(nuevoProducto); //Agrega el producto a la lista.
            pila.push(nuevoProducto); //Agrega el producto a la pila.
            Collections.sort(producto); //Se ordenan los productos ingresados por categoria.
            JOptionPane.showMessageDialog(null, "Producto agregado correctamente","SuperTienda",  JOptionPane.INFORMATION_MESSAGE);
            txt_ingresarProducto.setText("");//
            txt_ingresarPrecio.setText(""); // Se colocan los valores por defecto.
            cmb_categoria.setSelectedIndex(0);//
            holder = new PlaceHolder(txt_ingresarProducto, "Ingrese el nombre del producto");//
            holder = new PlaceHolder(txt_ingresarPrecio, "Ingrese el valor del producto");//
  
        }
        
    }//GEN-LAST:event_btn_agregarProductoActionPerformed

    private void txt_nombreModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreModificarActionPerformed

    private void btn_limpiarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarModificacionActionPerformed
        
        txt_nombreModificar.setText("");
        txt_precioModificacion.setText("");
        holder = new PlaceHolder(txt_nombreModificar, "Ingrese el nombre del producto");
        holder = new PlaceHolder(txt_precioModificacion, "Ingrese el valor del producto");
        
    }//GEN-LAST:event_btn_limpiarModificacionActionPerformed

    private void btn_aceptarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarModificacionActionPerformed
        
        String nombre = txt_nombreModificar.getText();
        String precio = txt_precioModificacion.getText();
        int tipo = cmb_modificarEliminar.getSelectedIndex();
        
        int verificacion = verificarProducto(nombre, precio, tipo); //Se verifica si el producto existe.
        
        if(verificacion == 1){ //Si existe
            
            ModificarProducto objModificar = new ModificarProducto();
            objModificar.txt_traeNombre.setText(nombre); //
            objModificar.txt_traePrecio.setText(precio); // Toma los valores ingresados y se los pasa a la vista ModificarProducto.
            objModificar.cmb_modificarCategoria.setSelectedIndex(tipo); //
            objModificar.setVisible(true);
            dispose();
            
        }else{ //Si no existe
            
            JOptionPane.showMessageDialog(null, "Error ! Producto no encontrado","SuperTienda",  JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_aceptarModificacionActionPerformed

    private void btn_actualizarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarListaActionPerformed
        
        //Se usa para imprimir toda la lista y colocarlo en el txtArea.
        StringBuilder strBuilder = new StringBuilder();
        
        for (int i = 0; i < producto.size(); i++) {
             
            if(producto.size()==0){
                
                txtArea_mostrarProducto.setText("No hay productos ingresados");
                
            }else{
                
                String nombre = producto.get(i).getProducto();
                //String precio = producto.get(i).getPrecio();
                int precio = producto.get(i).getPrecio();
                int categoria = producto.get(i).getCategoria();

                switch(categoria){

                    case 1:
                        strBuilder.append("Nombre: "+nombre+" Precio: $"+precio+" Categoria: Camisa"+"\n");
                    break;

                    case 2:
                        strBuilder.append("Nombre: "+nombre+" Precio: $"+precio+" Categoria: Camiseta"+"\n");
                    break;

                    case 3:
                        strBuilder.append("Nombre: "+nombre+" Precio: $"+precio+" Categoria: Pantalón"+"\n");
                    break;

                    case 4:
                        strBuilder.append("Nombre: "+nombre+" Precio: $"+precio+" Categoria: Vestido"+"\n");
                    break;

                    case 5:
                        strBuilder.append("Nombre: "+nombre+" Precio: $"+precio+" Categoria: Zapatos"+"\n");
                    break;

                    case 6:
                        strBuilder.append("Nombre: "+nombre+" Precio: $"+precio+" Categoria: Chaqueta"+"\n");
                    break;

                    case 7:
                        strBuilder.append("Nombre: "+nombre+" Precio: $"+precio+" Categoria: Medias"+"\n");
                    break;
            }
            }
        }
        
        txtArea_mostrarProducto.setText(strBuilder.toString());
        
    }//GEN-LAST:event_btn_actualizarListaActionPerformed

    private void btn_actualizarEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarEstadisticaActionPerformed
        
        StringBuilder strBuilder2 = new StringBuilder();
        strBuilder2.append("Total productos ingresados : "+producto.size()+"\n");//Se hacen las consultas de las estadisticas.
        strBuilder2.append("Primer producto ingresado : "+devolverPrimero()+"\n");//
        
        txtArea_estadistica.setText(strBuilder2.toString()); //Se colocan en la ventana.
        
    }//GEN-LAST:event_btn_actualizarEstadisticaActionPerformed

    private void btn_salirPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirPropietarioActionPerformed
        
        String decision = JOptionPane.showInputDialog("¿Seguro desea cerrar la sesión? Si/No"); //Cierra la sesión
        
        if(decision.toLowerCase().equals("si")){ //Si la respuesta es si.
            
            Login objLogin = new Login();
            objLogin.setVisible(true);
            dispose();
            
        }else if(decision.toLowerCase().equals("no")){ //Si la respuesta es no.
            
        }
        
    }//GEN-LAST:event_btn_salirPropietarioActionPerformed

    private void btn_aceptarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarSolicitudActionPerformed
        
        VistaCliente objCliente = new VistaCliente();
        objCliente.cola.remove().getProducto(); //Se remueve la solicitud creada desde el cliente.
        JOptionPane.showMessageDialog(null, "Solicitud atendida correctamente","SuperTienda",  JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btn_aceptarSolicitudActionPerformed

    private void btn_actualizarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarSolicitudActionPerformed
        
        //Se encarga de mostrar el primer elemento de la cola.
        VistaCliente objCliente = new VistaCliente();
        StringBuilder strBuilder = new StringBuilder();
  
            if(objCliente.cola.size()==0){
                
                txtArea_mostrarSolicitud.setText("No hay solicitudes en cola");
                
            }else{
                
                String nombre = objCliente.cola.peek().getProducto();
                int precio = objCliente.cola.peek().getPrecio();
                int categoria = objCliente.cola.peek().getCategoria();

                switch(categoria){

                    case 1:
                        strBuilder.append("Nombre: "+nombre+" Precio: $"+precio+" Categoria: Camisa"+"\n");
                    break;

                    case 2:
                        strBuilder.append("Nombre: "+nombre+" Precio: $"+precio+" Categoria: Camiseta"+"\n");
                    break;

                    case 3:
                        strBuilder.append("Nombre: "+nombre+" Precio: $"+precio+" Categoria: Pantalón"+"\n");
                    break;

                    case 4:
                        strBuilder.append("Nombre: "+nombre+" Precio: $"+precio+" Categoria: Vestido"+"\n");
                    break;

                    case 5:
                        strBuilder.append("Nombre: "+nombre+" Precio: $"+precio+" Categoria: Zapatos"+"\n");
                    break;

                    case 6:
                        strBuilder.append("Nombre: "+nombre+" Precio: $"+precio+" Categoria: Chaqueta"+"\n");
                    break;

                    case 7:
                        strBuilder.append("Nombre: "+nombre+" Precio: $"+precio+" Categoria: Medias"+"\n");
                    break;
            }
            }
            
        txtArea_mostrarSolicitud.setText(strBuilder.toString()); //Muestra la información en el txtArea.
        
    }//GEN-LAST:event_btn_actualizarSolicitudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        VistaPropietario objPropietario = new VistaPropietario();
        //objPropietario.cargarProducto();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPropietario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel actualizarCola;
    public javax.swing.JLabel atenderPrimero;
    public javax.swing.JButton btn_aceptarModificacion;
    public javax.swing.JButton btn_aceptarSolicitud;
    public javax.swing.JButton btn_actualizarEstadistica;
    public javax.swing.JButton btn_actualizarLista;
    public javax.swing.JButton btn_actualizarSolicitud;
    public javax.swing.JButton btn_agregarProducto;
    public javax.swing.JButton btn_limpiarModificacion;
    public javax.swing.JButton btn_limpiarProducto;
    public javax.swing.JButton btn_salirPropietario;
    public javax.swing.JLabel cerrarSesion;
    private javax.swing.JComboBox<String> cmb_categoria;
    public javax.swing.JComboBox<String> cmb_modificarEliminar;
    public javax.swing.JLabel datosProducto;
    public javax.swing.JLabel estadisticaTienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    public javax.swing.JLabel modificacionProducto;
    public javax.swing.JLabel solicitudes;
    public javax.swing.JTextArea txtArea_estadistica;
    public javax.swing.JTextArea txtArea_mostrarProducto;
    public javax.swing.JTextArea txtArea_mostrarSolicitud;
    public javax.swing.JTextField txt_ingresarPrecio;
    public javax.swing.JTextField txt_ingresarProducto;
    public javax.swing.JTextField txt_nombreModificar;
    public javax.swing.JTextField txt_precioModificacion;
    // End of variables declaration//GEN-END:variables
}
